stages:
    - build

master:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build

    script:
        - ./autogen.sh --enable-debug --enable-nautilus
        - make
