stages:
    - build

master:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build

    script:
        - ./autogen.sh --enable-debug --enable-nautilus
        - make

    artifacts:
        when: on_failure
        paths:
        - config.log
        expire_in: 2 days

gtk-doc:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build
    when: manual

    script:
        - ./autogen.sh --enable-nautilus --enable-gtk-doc
        - make

    artifacts:
        when: on_failure
        paths:
        - config.log
        expire_in: 2 days
